### ISSUE TITLE
readwrite option not working

### ISSUE THREAD

**Issue by muammar** [linux-apfs/linux-apfs-rw#17]
Thanks for this effort you are making by enabling apfs on Linux. I used your other tool to format an external hard disk, and everything seems to work. When I mount the newly formatted partition with: 

```
sudo mount -o readwrite /dev/sdc1 Backup 
```

And I try to create anything either with `sudo` or as a regular user; it does not let me do that.

```

mkdir: cannot create directory ‘hola’: Read-only file system
```

PS. This is on Debian Unstable.

**Comment by eafer** [comment]
That's weird. Any output on dmesg?

**Comment by muammar** [comment]
```
[   66.504090] ucsi_acpi USBC000:00: PPM init failed (-110)
[   86.067204]  sdb: sdb1
[  105.562233]  sdb: sdb1
[  327.690887] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null)
[  423.904292]  sdb: sdb1
[  440.258117]  sdb: sdb1
[  530.870511] APFS (26g): experimental write support is enabled
[  535.085950] APFS (26g): large devices are not supported
[  535.085953] APFS (26g): aborting transaction
```

Large devices are not supported. That’s the problem. This is a 2TB hard drive.

**Comment by eafer** [comment]
I just pushed a patch to the mkfs, when you can let me know if it fixed your problem. One thing you should know: large containers above 1.4Tb or so may be usable with my module alone, but the official implementation of apfs will probably reject them. I'll fix this eventually, but I don't have the time now.

**Comment by muammar** [comment]
@eafer sorry that I got back to you late. I tried again, but it still does not work. 

```
[  149.340916] sd 10:0:0:0: [sdb] Spinning up disk...
[  150.362462] .....ready
[  154.458851] sd 10:0:0:0: [sdb] 3906963456 512-byte logical blocks: (2.00 TB/1.82 TiB)
[  154.459092] sd 10:0:0:0: [sdb] Write Protect is off
[  154.459097] sd 10:0:0:0: [sdb] Mode Sense: 47 00 10 08
[  154.459376] sd 10:0:0:0: [sdb] No Caching mode page found
[  154.459385] sd 10:0:0:0: [sdb] Assuming drive cache: write through
[  154.522900]  sdb: sdb1
[  154.524696] sd 10:0:0:0: [sdb] Attached SCSI disk
[  356.970552]  sdb: sdb1
[  515.548842] APFS (26g): experimental write support is enabled
[  518.284555] APFS (26g): unable to read container object map
[  518.284564] APFS (26g): aborting transaction
(base) 

```

What could be happening in this case? I tried mounting the hard disk formatted with macOS, and also with your tools, and in both cases, I am unable to write. I will just check the disk and try again.

**Comment by alexmyczko** [comment]
@muammar I'm trying to create a debian package, if someone wants to help? https://mentors.debian.net/package/linux-apfs-rw/

**Comment by muammar** [comment]
> @muammar I'm trying to create a debian package, if someone wants to help? https://mentors.debian.net/package/linux-apfs-rw/

I would be interested and if it works I can try to help you upload it to the Debian archives (I am a DD). I will install it on my Debian unstable and check if I get writing support.

**Comment by alexmyczko** [comment]
i guess it's far from ready, but after you install, i'm able to run `dkms build linux-apfs-rw/0+git20210928` but somehow couldn't get a kernel module, to modprobe, any help is welcome.

**Comment by alexmyczko** [comment]
@muammar i think this one looks good already: https://mentors.debian.net/package/apfsprogs/ (except for the missing unicode license part, needs clarification with upstream)

**Comment by eafer** [comment]
@alexmyczko Thanks for your effort, it would be nice to see this packaged for Debian. I don't have any experience with that, but let me know if I can help. You should start a separate issue though, since Muammar's problem is not yet fixed.

**Comment by Williamtung1** [comment]
Hello! I also have a problem not abling to mount a partition as read-write in Arch Linux (Manjaro) 
That's the code I used:
<code>sudo mount -o cknodes,vol=4,readwrite /dev/sdb2 /home/william/Macintosh</code>
I can't write files to the partition as well. 
With mkdir,
 <code>dmesg: read kernel buffer failed: Operation not permitted</code>

**Comment by AdityaGarg8** [comment]
Hello
Do I need to use the [apfsprogs](https://github.com/linux-apfs/apfsprogs) tools as well to enable write support?

**Comment by eafer** [comment]
> Do I need to use the [apfsprogs](https://github.com/linux-apfs/apfsprogs) tools as well to enable write support?

No, you need to use the readwrite mount option. The README explains it, but
be careful, it's likely to cause some corruption.

**Comment by AdityaGarg8** [comment]
Well I tried with readwrite option on a 4GB APFS formatted USB drive, but was not successful.

BTW, I noticed there was a demand for a Debian package for the same. I am hosting this driver in my [APT repo](https://github.com/AdityaGarg8/t2-ubuntu-repo). It shall be updated regularly since I have also set a scheduled job to look for updates from this repo of yours and publish a newer version if available.

**Comment by AdityaGarg8** [comment]
Are there any logs that I can share to fix my write issue?

**Comment by AdityaGarg8** [comment]
@eafer 

This is what I get on mounting as readwrite

```
aditya@MacBook:~$ sudo mount -o readwrite /dev/sda2 /mnt
[sudo] password for aditya: 
mount: /mnt: WARNING: source write-protected, mounted read-only.
```

And my dmesg

```
aditya@MacBook:~$ sudo dmesg | grep apfs
[  101.590889] apfs: loading out-of-tree module taints kernel.
[  101.590937] apfs: module verification failed: signature and/or required key missing - tainting kerne
```

**Comment by AdityaGarg8** [comment]
Also, the name of my APFS volume is not being displayed in Files app, and GNOME disks also marks my USB Drive as no mounted, in-spite of it actually being mount.

**Comment by eafer** [comment]
> ```
> ***@***.***:~$ sudo mount -o readwrite /dev/sda2 /mnt
> [sudo] password for aditya: 
> mount: /mnt: WARNING: source write-protected, mounted read-only.
> ```

This doesn't seem to be an apfs problem. Your device at /dev/sda2 appears
to be on read-only mode for some reason. Maybe it has a physical switch for
that?

> Also, the name of my APFS volume is not being displayed in Files app

APFS containers don't have a label themselves. You do have a label for each
volume, but a single partition can hold multiple volumes, so I don't think
there is any sane way for linux file managers to report that. If they wanted
they could report the gpt partition label when it's available, but that
doesn't involve APFS.

> GNOME disks also marks my USB Drive as no mounted, in-spite of it actually being mount.

I have no idea how file managers tell apart mounted and unmounted devices,
but it probably doesn't involve the driver directly. Maybe they check
/proc/mounts. I just checked on thunar and it seems to work, but not every
single time. I'll try to look into it at some point, but maybe you'll get
faster results if you just ask the nautilus devs.

**Comment by AdityaGarg8** [comment]
> This doesn't seem to be an apfs problem. Your device at /dev/sda2 appears to be on read-only mode for some reason. Maybe it has a physical switch for that?

No it doesn't have a physical switch. I had formatted it using macOS 12 to APFS. Should I use apfsprogs?

**Comment by eafer** [comment]
> No it doesn't have a physical switch

What do you get if you run `blockdev --getro /dev/sda2`? I think you'll get a 1, which means read-only. I don't know why, but maybe there's something on dmesg that explains it.

**Comment by AdityaGarg8** [comment]
> What do you get if you run `blockdev --getro /dev/sda2`? I think you'll get a 1, which means read-only. I don't know why, but maybe there's something on dmesg that explains it.

```
aditya@MacBook:~$ sudo blockdev --getro /dev/sda2
[sudo] password for aditya: 
0
```

I am getting a 0.

**Comment by eafer** [comment]
And it still doesn't mount? Weird. What about after you try to mount with `readwrite`, do you still get a 0?

**Comment by AdityaGarg8** [comment]
Yeah, I am still getting a 0.

I just noticed that I am able to rename files after mounting as readwrite. But I am not able to copy new files or edit existing files.

**Comment by AdityaGarg8** [comment]
```
aditya@MacBook:/mnt$ sudo cp /media/aditya/"TOSHIBA EXT1"/ubuntu/iso-firmware.deb ./
cp: cannot create regular file './iso-firmware.deb': Read-only file system
```

**Comment by AdityaGarg8** [comment]
I did manage to write one file luckily, but now its refusing to even rename.

**Comment by eafer** [comment]
You can rename files on a read-only mount? What do you get for your apfs filesystem on /proc/mounts? If you can also send me all your dmesg since the first mount.

**Comment by eafer** [comment]
But are you still getting `mount: /mnt: WARNING: source write-protected, mounted read-only`, or is that gone?

**Comment by AdityaGarg8** [comment]
> But are you still getting `mount: /mnt: WARNING: source write-protected, mounted read-only`, or is that gone?

I am not getting this now.

**Comment by AdityaGarg8** [comment]
I reformatted the USB to APFS again using macOS and added a text file there. Now, I was able to rename, and even edit the file. But, as I tried to copy a debian package to the USB, it suddenly became read-only again.

**Comment by AdityaGarg8** [comment]
```
aditya@MacBook:~$ sudo dmesg | grep apfs
[  103.578879] apfs: loading out-of-tree module taints kernel.
[  103.578939] apfs: module verification failed: signature and/or required key missing - tainting kernel
aditya@MacBook:~$ sudo dmesg > apfs.log
aditya@MacBook:~$ sudo dmesg | grep APFS
[  186.334622] APFS (33g): experimental write support is enabled
[  203.507090] APFS: space manager is versioned
[  227.194568] APFS (33g): internal pool seems full
[  227.194572] APFS (33g): unable to read container object map
[  227.194574] APFS (33g): aborting transaction
[  227.194576] APFS (33g): failed to delete orphan inode 0x9e
```

**Comment by AdityaGarg8** [comment]
Do you want the full dmesg?

**Comment by AdityaGarg8** [comment]
> 

```
/dev/sda2 /mnt apfs ro,relatime 0 0
```

I am getting this in `/proc/mounts`

**Comment by eafer** [comment]
By any chance, is the volume close to being full?

> Do you want the full dmesg?

No need, thanks. It's a problem with the driver then, no idea why you were getting the `source write-protected` message before. The mount becomes read-only as soon as it finds something weird, to try to avoid corrupting your data. I'll look into it as soon as I'm done working on snapshots.

**Comment by AdityaGarg8** [comment]
> By any chance, is the volume close to being full? What's the size?
It's around 4Gbs. Not close to full since it has only 1 text file.

**Comment by eafer** [comment]
If you can send me an image for the freshly formatted disk it would help a lot.

**Comment by eafer** [comment]
You can first wipe all data in the usb device with `dd if=/dev/zero of=/dev/sda2`. Then format the device on apfs the same way you always do. Then run `dd if=/dev/sda2 of=img` and you'll get a 4GB image file called `img`. You can send me that, or compress it first to make it easier.

**Comment by AdityaGarg8** [comment]
I'll do it later when I shall get free.

**Comment by AdityaGarg8** [comment]
> Thanks, no rush. Make sure you understand what you are doing, if you zero the wrong device you'll lose data.

Yeah I got it.

**Comment by AdityaGarg8** [comment]
Will I have to do `dd if=/dev/zero of=/dev/sda2`, cause it's taking a lot of time.

**Comment by eafer** [comment]
> Will I have to do dd if=/dev/zero of=/dev/sda2, cause it's taking a lot of time.

That's just in case you have private data left on the device, that was deleted but can be recovered. It should also make the final compressed file much smaller. But you can skip it if you prefer.

**Comment by eafer** [comment]
I'm thinking, maybe /dev/sda2 is larger than 4GB, and you just made a smaller container inside of it? Because otherwise I can't see why this would take so long.

**Comment by AdityaGarg8** [comment]
> You can first wipe all data in the usb device with `dd if=/dev/zero of=/dev/sda2`. Then format the device for apfs the same way you always do. Then run `dd if=/dev/sda2 of=img` and you'll get a 4GB image file called `img`. You can send me that, or compress it first to make it easier.

https://drive.google.com/file/d/1qV9NYrkb6yA-JPS9ugxdOaUiz7dV0BnT/view?usp=sharing

You can download the image from here. Please inform me when you get it cause I want to free up my drive's space so I shall delete it after you get it.

**Comment by eafer** [comment]
> You can download the image from here. Please inform me when you get it cause I want to free up my drive's space so I shall delete it after you get it.

Got it, thanks. I can reproduce your issue, I'll look into it now.

**Comment by eafer** [comment]
@AdityaGarg8 I just pushed a patch, when you can let me know if it solves your problem.

**Comment by AdityaGarg8** [comment]
I am having a new issue now. Now it doesn't become read-only, but the file it copies to the USB actually doesn't get copied. Eg:- I copied a short 20Mb video and it failed to play. Infact, I ejected and replugged my USB, it was gone.

```
aditya@MacBook:~$ sudo dmesg | grep apfs
[sudo] password for aditya: 
[  933.979984] apfs: loading out-of-tree module taints kernel.
[  933.980029] apfs: module verification failed: signature and/or required key missing - tainting kernel
aditya@MacBook:~$ sudo dmesg | grep APFS
[ 1029.349915] APFS (31g): experimental write support is enabled
[ 1036.327987] APFS: space manager is versioned
[ 1192.982724] APFS (31g): transaction commit failed
[ 1192.982726] APFS (31g): aborting transaction
[ 1213.092607] APFS (31g): experimental write support is enabled
[ 1310.425643] APFS (31g): transaction commit failed
[ 1310.425644] APFS (31g): aborting transaction
```

This is what I got.

**Comment by AdityaGarg8** [comment]
For some reason I also am not able to unmount my USB if it is mounted in readwrite mode.

**Comment by eafer** [comment]
Weird, both work fine over here with your image. Can you tell me the exact steps you followed to get there? Did you just copy the file to the fresh image? If that's the case, maybe the problem is with your kernel version, which one are you using?

**Comment by AdityaGarg8** [comment]
What I did was

```
sudo unmount /dev/sda2
sudo mount /dev/sda2 /mnt
sudo cp /path/to/file /mnt
```

I am using kernel version 6.0.2

**Comment by eafer** [comment]
But had you done anything to the filesystem before the first unmount?

> I am using kernel version 6.0.2

I'll try to test this in a 6.0 kernel and get back to you, it may take a few days though.

**Comment by eafer** [comment]
It could be that the text file mattered though. If you can, just format the usb on macos, and then try to write the video file with my driver.

**Comment by AdityaGarg8** [comment]
If you want I can test on a 5.15.x kernel later.

**Comment by AdityaGarg8** [comment]
I finally am able to diagnose the issue. Actually `cp` command falsely reports the file as copied, but actually it doesn't copy. Now, I used to simply plug out my USB so I faced the issue I told you about. Now, this time I unmounted the USB using the terminal, and the lights on the USB which blink when data is written started blinking. The terminal was stuck at unmounting the USB, but I patiently waited. After a few moments the drive successfully unmounted. I remounted it again and this time writes were a success. I checked the same in macOS and the md5sums of the files copied were matching the original, so I guess there wasn't any data corruption as well.

**Comment by AdityaGarg8** [comment]
I guess it starts writing after I send the `umount` command

**Comment by AdityaGarg8** [comment]
```
aditya@MacBook:~/Downloads/Renal/02 Acid-Base$ sudo dmesg | grep APFS
[  475.725224] APFS (31g): experimental write support is enabled
[  480.658690] APFS: space manager is versioned
[  649.802397] APFS (31g): experimental write support is enabled
```

`dmesg` also looks good.

**Comment by eafer** [comment]
Ah, yes, technically I don't have to write the files to disk until the unmount. It would still be a good idea to trigger commits regularly, but it's not a priority right now. If you don't want to unmount you can also use `sync` for this purpose.

**Comment by AdityaGarg8** [comment]
> Ah, yes, technically I don't have to write the files to disk until the unmount. It would still be a good idea to trigger commits regularly, but it's not a priority right now. If you don't want to unmount you can also use `sync` for this purpose.

Oh I though it was a bug. The driver looks good then :)

**Comment by AdityaGarg8** [comment]
> Ah, yes, technically I don't have to write the files to disk until the unmount. It would still be a good idea to trigger commits regularly, but it's not a priority right now. If you don't want to unmount you can also use `sync` for this purpose.

Hi @eafer 
Could you tell me whether this issue is due to the driver or userspace apps?

**Comment by eafer** [comment]
> Could you tell me whether this issue is due to the driver or userspace apps?

The issue is in the driver. But keep in mind that, even with a proper
implementation, pulling out the usb without unmounting is always risky.

**Comment by AdityaGarg8** [comment]
> Could you tell me whether this issue is due to the driver or userspace apps?
> The issue is in the driver. But keep in mind that, even with a proper implementation, pulling out the usb without unmounting is always risky.

Thanks for clarifying.
Also can we have a module parameter to enable writes as mentioned here :- https://github.com/linux-apfs/linux-apfs-rw/issues/33#issue-1469505496

If you want I can try doing the same and send a PR if I am able to succeed.

**Comment by eafer** [comment]
@muammar The latest release (0.3.6) should have support for filesystems of up to 6.7 TB. It's been several years and I don't know if you still care, so I'm just closing this without waiting for a reply. Feel free to reopen if needed.
