### ISSUE TITLE
Nautilus file manager is unable to unmount the APFS partition.

### ISSUE THREAD

**Issue by blickers** [linux-apfs/linux-apfs-rw#58]
System: Debian 12
Linux Kernel: 6.6
Desktop Environment: GNOME 43

One of the partitions on my USB hard disk was formated as APFS using macOS. When the device is plugged in, Linux will automatically mount it, similar to how it handles other partition types like NTFS or Exfat. But when attempting to unmount the APFS partition through the Nautilus file manager's left sidebar, clicking on the "Disconnect" button triggers a dialog displaying the message "Unable to unmount"  (see screenshot). Nautilus will exhibit an error message on the dialog indicating that the partition is not mounted, even though it has indeed been mounted.

If the computer is awakened from suspend mode, the APFS partition on my USB hard drive will automatically be remounted to a new mounting point, resulting in the repeated mounting of the partition.

Except for linux-apfs-rw, other partition types do not pose this issue. So, I believe there might be a bug present in the current linux-apfs-rw kernel driver.

![Screenshot from 2023-11-29 23-57-30](https://github.com/linux-apfs/linux-apfs-rw/assets/54505861/a110c797-580e-4ba8-8d69-45170162e562)

![2](https://github.com/linux-apfs/linux-apfs-rw/assets/54505861/108a35f0-0b28-41a7-8faf-4a6b45e8fcb8)

**Comment by eafer** [comment]
Have you tried unmounting the partition from the terminal? Are you getting any output in dmesg?

**Comment by eafer** [comment]
I have no idea how Nautilus unmounts stuff. I would have expected it to just call libmount, so it should have been the same as using the terminal, but that's clearly not the case. I see the same issue on Thunar, so maybe the problem is in glib? It's hard to imagine how this could be the driver's fault, since the device gets listed correctly on `/proc/self/mountinfo`, which is the only file that seems to get parsed to check for mounts. I'll keep digging though.

> Another concern is that Linux does not mount APFS partitions to the mount point specified by the volume label. Instead, it uses the partition UUID.

The UUID in use here is the UUID for the container, not for the individual volume that gets mounted (which is the default volume 0). The container has no label itself. It would be better if Nautilus showed the uuid and label for the individual mounted volume, but I don't think there's anything I can do about that. I don't know how they get the labels, but it's probably userland stuff.

**Comment by eafer** [comment]
@blickers I just pushed a patch for this issue to the development branch if you want to try it out. It's not prefect though, but I think it should work at least for a single volume. Thank you for the report.

**Comment by blickers** [comment]
The patch is functioning as expected. We appreciate your excellent work!

**Comment by ernstki** [comment]
Do either of you have any intuition about how to work around this problem with userspace tools (even run as root)?

I cloned this repository last November, so I have e3c8721, but I'm still experiencing this problem on elementary OS 7.1, which is basically Ubuntu 22.04 under the hood.

[Here's a similar issue](https://unix.stackexchange.com/questions/680902/btrfs-automounted-and-mounted-via-gnome-disks-error-finding-object-for-block) described on Stack Exchange, where the purported solution was to use `udisksctl`, but no joy:

```console
$ mount | grep apfs
/dev/nvme0n1p2 on /media/me/3668ed21-1d67-0429-a82a-c3e2a1590e92 type apfs (ro,nosuid,nodev,relatime,uhelper=udisks2)
/dev/sda2 on /media/me/b525c4f3-66e0-e141-a771-053831d6b623 type apfs (ro,nosuid,nodev,relatime,uhelper=udisks2)

$ udisksctl unmount --block-device /dev/sda2
Error unmounting /dev/sda2: GDBus.Error:org.freedesktop.UDisks2.Error.NotMounted: Device `/dev/sda2' is not mounted

$ udisksctl unmount --block-device /dev/nvme0n1p2
Error unmounting /dev/nvme0n1p2: GDBus.Error:org.freedesktop.UDisks2.Error.NotMounted: Device `/dev/nvme0n1p2' is not mounted
````

I _guess_ the solution is just reboot (and pull the latest changes from this repo and re-install)… but I thought I'd ask anyway.
